[package]
name = "livestream-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
chrono = "0.4.43"
env_logger = "0.11.9"
ffmpeg-sys-next = { version = "8.0.1", default-features = false, features = ["avcodec", "avformat"] }
openssl = "0.10.75"
log = "0.4.29"
minio = "0.3.0"
prost = "0.14.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tonic = "0.14.3"
tonic-prost = "0.14.3"
tokio-stream = { version = "0.1.18", features = ["sync", "fs"] }
async-stream = "0.3.6"
redis = { version = "1.0.3", features = ["tokio-comp", "connection-manager"] }

[build-dependencies]
tonic-prost-build = "0.14.3"
