services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URI: redis://redis-service
      MINIO_URI: http://minio-service:9000
      MINIO_ACCESSKEY: admin
      MINIO_SECRETKEY: 123456MinIO
      MINIO_BUCKET: videos
      RUST_LOG: info
      GRPC_PORT: 50051
    ports:
      - "50051:50051"
      - "4000-4100:4000-4100/udp"
    volumes:
      - ../..:/workspaces:cached
    networks:
      - devcontainer-net
    command: sleep infinity

  minio-service:
    image: minio/minio:latest
    container_name: minio-service
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123456MinIO
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - devcontainer-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-service:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - devcontainer-net

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_ACCEPT_LICENSE=true
    depends_on:
      - redis-service
    networks:
      - devcontainer-net

volumes:
  minio-data:

networks:
  devcontainer-net:
    driver: bridge
